### ISSUE TITLE
readFileSync

### ISSUE THREAD

**Issue by maxogden** [dominictarr/noderify#7]
```js
module.exports = protobuf(fs.readFileSync(__dirname + '/../schema.proto', 'utf-8'))
```

(source https://github.com/mafintosh/hyperlog/blob/master/lib/messages.js)

causes:

```sh
$ node clibundle.js 
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/messages.js/../schema.proto'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at __dirname.1IQXSf+9lwpLPTCx4bHiZOYx2KUuLvRgscsJuVvAIZI= (/Users/max/src/js/dat/clibundle.js:5372:30)
    at load (/Users/max/src/js/dat/clibundle.js:11:5)
    at /Users/max/src/js/dat/clibundle.js:15:29
    at __dirname.I/DoqOb+gWfGE7uN7ohxxxsIoP8Bqdkz1sgIW+9zEno= (/Users/max/src/js/dat/clibundle.js:14216:16)
    at load (/Users/max/src/js/dat/clibundle.js:11:5)
    at /Users/max/src/js/dat/clibundle.js:15:29
    at __dirname.OxzcI+C7mCKR4BGZJCd26I7MPcKNDreQm49RI7PqVto= (/Users/max/src/js/dat/clibundle.js:22413:16)
```

could it keep the original directory metadata around and fall back to reading the file?

**Comment by dominictarr** [comment]
I remember when we where discussing how to implement this with browserify, and we all decided that the best way was just to polyfil `fs` so that it preloaded absolute paths into the bundle. It made sense, since the browser didn't have `fs` support anyway -- however, in noderify you *do* have access to the filesystem,
so polyfilling `fs` isn't as appropiate.

What would work better would be if you could require other files and they loaded as strings, for example.
This was suggested at that time but we turned it down because it wasn't how node worked.
I guess you could transform absolute requires, but do it statically, so that you never polyfilled `fs`.

here is how brfs works: https://github.com/substack/brfs/blob/master/index.js#L24-L35
but what would be better, in this case is to transform into something that was treated the same as require.
